In [1]:
import numpy as np

Numpy indexing and slicing of vectors

In [2]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[6]

17

In [5]:
arr[:5]

array([11, 12, 13, 14, 15])

In [8]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

Numpy indexing and slicing of matrix

In [10]:
arr = np.arange(1,31).reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [13]:
arr[0, 0]

1

In [14]:
arr[0:2, 1:3]

array([[2, 3],
       [7, 8]])

In [15]:
slice = arr[3:, 3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [16]:
arr[:

array([ 3,  8, 13, 18, 23, 28])

Boolean indexing

In [27]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [28]:
bool_index = arr %2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [29]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])