In [1]:
import numpy as np

Basic array

In [3]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [6]:
a = [1, 2, 3.5, "Hello"]
a

[1, 2, 3.5, 'Hello']

In [7]:
np.array(a)

array(['1', '2', '3.5', 'Hello'], dtype='<U32')

In [9]:
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array generation function

In [11]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr = np.arange(1, 11, 2)
arr

array([1, 3, 5, 7, 9])

In [15]:
arr = np.zeros((6, 6,))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
arr  = np.ones((4, 3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
arr = np.linspace(0, 1, 100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

Random generation functions

In [25]:
np.random.rand(10)

array([0.01090462, 0.03189218, 0.44209652, 0.08167712, 0.93333798,
       0.11536472, 0.39333783, 0.26193578, 0.29442102, 0.24667244])

In [27]:
np.random.randn(10)

array([-0.06230314, -1.12781245, -0.4097189 , -0.51078625,  1.60835108,
       -0.58197261,  0.19046916, -0.35073554, -2.20345789, -1.37447869])

In [28]:
np.random.randint(10, 20, 10)

array([11, 12, 17, 14, 11, 16, 15, 13, 12, 19])

Array attributes

In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr.shape

(3, 3)

In [31]:
arr.size

9

In [32]:
arr.dtype

dtype('int32')

Array Methods

In [33]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr.min()

1

In [35]:
arr.max()

9

In [36]:
arr.sum()

45

In [38]:
np.sum(arr, axis = 0) #column 

array([12, 15, 18])

In [39]:
np.sum(arr, axis = 1) #row

array([ 6, 15, 24])

In [40]:
arr.mean()

5.0

In [41]:
arr.std()

2.581988897471611

In [42]:
arr.argmax()

8

In [43]:
arr.argmin()

0

Reshaping and resizing

In [49]:
arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [52]:
arr = arr.reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])