In [1]:
import numpy as np

Valid Sudoku

In [2]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2], 
    [6, 7, 2, 1, 9, 5, 3, 4, 8], 
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3], 
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [3]:
b = np.sum(s, axis = 1)
[b == 45]

[array([ True,  True,  True,  True,  True,  True,  True,  True,  True])]

In [4]:
for i in b:
    if i != 45:
        print("sudoku is not valid")
        break
    else:
        print("For rows it is valid")

For rows it is valid
For rows it is valid
For rows it is valid
For rows it is valid
For rows it is valid
For rows it is valid
For rows it is valid
For rows it is valid
For rows it is valid


In [5]:
c = np.sum(s, axis = 0)
for i in b:
    if i != 45:
        print("sudoku is not valid")
        break
    else:
        print("For columns it is valid")

For columns it is valid
For columns it is valid
For columns it is valid
For columns it is valid
For columns it is valid
For columns it is valid
For columns it is valid
For columns it is valid
For columns it is valid


In [6]:
s[:3, :3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [7]:
s[:3, 3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [8]:
s[:3, 6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [9]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3, j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


General Questions

In [10]:
import numpy as np

# columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],  #student1
    [19, 92, 88],  #student2
    [17, 76, 95],  #student3
    [18, 65, 70],  #student4
    [20, 90, 85]   #student5
])

In [11]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [12]:
#Find the average age of students.
np.mean(data[:, 0])

18.4

In [13]:
#Extract Math Marks of all students.
data[:, 1]

array([85, 92, 76, 65, 90])

In [14]:
#Find the highest Science mark.
np.max(data[:, 2])

95

In [15]:
#Get details of the student who scored more than 90 in math.

data[data[:, 1] > 90]

array([[19, 92, 88]])

In [16]:
#Increase Math marks of all students by 5.
data[:,1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [17]:
# Find how many students are younger than 19.
len(data[data[:, 0] < 19])

3

In [18]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:, 1:], axis = 0)

array([86.6, 83.2])

In [19]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:, 1] >= 80) & (data[:, 2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [20]:
# Replace all science marks < 75 with 0.
data[:, 2][data[:, 2] < 75] = 0

In [21]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])