# Array Creation & Attributes

In [20]:
# 1. Import the Numpy library with the alias np.
import numpy as np

In [22]:
# 2. Create a 1D Numpy array from the python list[1, 2, 3, 4, 5].
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [26]:
# 3. Create a 1D array of 10 zeros.
arr = np.zeros(10, dtype=int)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
# 4. Create a 3X3 array filled with ones.
arr = np.ones((3, 3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
# 5. Create an array of all even integers from 10 to 50.
arr = np.arange(10, 51, 2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [33]:
# 6. Create a 3X3 matrix with values ranging from 0 to 8.
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
# 7. Create a 4X4 identity matrix.
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
# 8. Create an array of 5 numbers evenly spaced between 0 to 1.
arr = np.linspace(0, 1, 5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [55]:
# 9. Create a 3X4 array filled with random numbers between 0 to 1.
arr = np.random.rand(3, 4)
arr

array([[0.16964842, 0.43128932, 0.8198002 , 0.15385293],
       [0.97584483, 0.72008311, 0.08674372, 0.67803415],
       [0.55902661, 0.15915098, 0.21844881, 0.61838943]])

In [56]:
# 10. Create a 5X5 array with random integers from 1 to 100.
arr = np.random.randint(1, 101, size =( 5, 5))
arr

array([[92, 17, 37, 97, 50],
       [83, 84, 92, 30, 57],
       [25, 42, 17, 21, 47],
       [ 4, 44, 96, 91, 87],
       [45, 74, 97, 60, 29]])

In [57]:
# 11. Given the array arr = np.arange(25).reshape(5, 5). Find its shape.
arr = np.arange(25).reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
arr.shape

(5, 5)

In [59]:
# 12. For the same array arr, find its data type.
arr.dtype

dtype('int32')

In [60]:
# 13. For the same array arr, find the total number of elements.
arr.size

25

In [63]:
# 14. Create the array[1, 2, 3] but make sure its data type is float.
arr = np.array([1, 2, 3], dtype= float)
arr

array([1., 2., 3.])

In [67]:
# 15. Convert the data type of an existing integer array to float.
int_arr = np.array([1, 2, 3])

In [68]:
arr = int_arr.astype(float)

In [69]:
arr

array([1., 2., 3.])